# Site settings
author: Zach Paul
title: Zach Paul's Data Science Journey
header-img: img/home-bg.png
email: zacharypaul42@gmail.com
copyright_name: Zach Paul
description: > # this means to ignore newlines until "baseurl:"
  A log for recounting my thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zpaul10

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
